field: 969890a0-f328-43b4-b8f6-8d1d6724eead # Content Blocks
fieldLayouts:
  ab30d850-cadc-40a8-a136-fbd9a543115f:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 5c20d381-a8d2-4a59-bc76-54e44a4e89ae # Embed
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: cfa711ea-37be-4ee3-8f70-2e924139dcd2
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: e0274974-7a35-4dd8-8f35-48c0359ff8ee
        userCondition: null
fields:
  5c20d381-a8d2-4a59-bc76-54e44a4e89ae: # Embed
    columnSuffix: dmjwmmwk
    contentColumnType: text
    fieldGroup: null
    handle: embed
    instructions: null
    name: Embed
    searchable: false
    settings:
      url: ''
    translationKeyFormat: null
    translationMethod: none
    type: wrav\oembed\fields\OembedField
handle: embed
name: Embed
sortOrder: 5
