fieldLayouts:
  b7e8066f-16a8-471c-b175-5e493a86c9c0:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 2a697c57-0c49-42b5-a393-b7a925808904
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: e1bcf984-ae8b-43db-a36b-783d963dd6be # Lead
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 33c3c0ec-87cd-4ea2-adab-d0b4667ddf08
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            type: craft\fieldlayoutelements\HorizontalRule
            uid: c46c2af1-963b-4b09-bc9d-d9eac9c5d52f
            userCondition: null
          -
            elementCondition: null
            fieldUid: 969890a0-f328-43b4-b8f6-8d1d6724eead # Content Blocks
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5ba250d7-a490-4f20-aec1-b3164cb50f83
            userCondition: null
            warning: null
            width: 100
        name: Inhalt
        uid: 1c160829-c442-4784-b4a6-187b26e02a40
        userCondition: null
handle: blog
hasTitleField: true
name: Blog
section: 3f6076cf-bc5d-4907-914e-41369bb3676b # Page
sortOrder: 2
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
