fieldLayouts:
  c6162791-db20-4ea1-88eb-cc1602e0b7b4:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: c9c8190e-7f10-4e65-8cdc-2546cdffc1e5
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 969890a0-f328-43b4-b8f6-8d1d6724eead # Content Blocks
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 588c4ab1-c1d0-439e-b9b3-0acbc007e379
            userCondition: null
            warning: null
            width: 100
        name: Inhalt
        uid: 1327f8d5-e6b1-42f7-8df9-362a68984280
        userCondition: null
handle: default
hasTitleField: true
name: Standard
section: 3f6076cf-bc5d-4907-914e-41369bb3676b # Page
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
