baseUrl: $PRIMARY_SITE_URL
enabled: true
handle: deutsch
hasUrls: true
language: de-CH
name: 'Chance Digitalität'
primary: true
siteGroup: fe794aba-5bf0-44ef-a823-0fc9cc8fb93e # Chance Digitalität
sortOrder: 1
