fieldLayouts:
  422ab86d-2917-4747-860c-e0bc10fe51ee:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: ae728292-0a74-40b3-bdd9-e0812ea652f6
            userCondition: null
            warning: null
            width: 100
        name: Inhalt
        uid: 4ff42d05-819d-4d9c-9a9f-c001bca81a14
        userCondition: null
fs: images
handle: images
name: Images
sortOrder: 4
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: ''
