columnSuffix: null
contentColumnType: string
fieldGroup: c0316fa8-d510-429a-8e98-9994a6bc7e1f # Common
handle: contentBlocks
instructions: null
name: 'Content Blocks'
searchable: false
settings:
  contentTable: '{{%matrixcontent_contentblocks}}'
  maxBlocks: null
  minBlocks: null
  propagationKeyFormat: null
  propagationMethod: language
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
