columnSuffix: hggewfch
contentColumnType: text
fieldGroup: 0f4f23be-0b8a-4ac4-94f0-8f934ce349c8 # Home
handle: lead
instructions: null
name: Lead
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: false
  columnType: null
  initialRows: 4
  multiline: false
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: language
type: craft\fields\PlainText
