changedFieldIndicator: 389841827
field: 6efa6df0-066e-4613-806f-9beddaf00eca # Raster
fieldLayouts:
  b86d17e1-9549-49fa-9491-41ad2191b469:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 723399b6-47d6-4bd9-b59a-c61c56cdaa44 # Kopfzeile
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 29a2b690-61b8-4fd2-aa58-766f0ad66c63
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 05d06e7e-2c5c-4332-8ae4-d93af318dadf # Bild
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c318607b-a486-4606-a8e2-eade8a15e09c
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: f7c1d3c4-fb65-4ead-83b4-ee3cf63d98e3 # Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4c39f963-be4e-4b06-9ba8-61973d0d32eb
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 3dd695cd-937f-432b-a962-8697fc5a70bf # Website
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9fb0d44e-2999-4ccf-9e22-53085bbbf392
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 24d4b9b7-9282-4440-af0d-426ff9d21156
        userCondition: null
fields:
  3dd695cd-937f-432b-a962-8697fc5a70bf: # Website
    columnSuffix: hxxplfhf
    contentColumnType: string(255)
    fieldGroup: null
    handle: website
    instructions: null
    name: Website
    searchable: false
    settings:
      maxLength: 255
      types:
        - url
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Url
  05d06e7e-2c5c-4332-8ae4-d93af318dadf: # Bild
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: image
    instructions: 'Leer lassen, falls nicht benötigt.'
    name: Bild
    searchable: false
    settings:
      allowSelfRelations: false
      allowSubfolders: false
      allowUploads: true
      allowedKinds: null
      branchLimit: null
      defaultUploadLocationSource: 'volume:d4cdab7c-bb04-4a50-bea1-4fe6353344c0' # Logos
      defaultUploadLocationSubpath: null
      localizeRelations: false
      maintainHierarchy: false
      maxRelations: 1
      minRelations: null
      previewMode: full
      restrictFiles: false
      restrictLocation: false
      restrictedDefaultUploadSubpath: null
      restrictedLocationSource: 'volume:85e7b218-d803-45ff-92b4-7fc6e3454d22' # About
      restrictedLocationSubpath: null
      selectionCondition:
        __assoc__:
          -
            - elementType
            - craft\elements\Asset
          -
            - fieldContext
            - global
          -
            - class
            - craft\elements\conditions\assets\AssetCondition
      selectionLabel: null
      showSiteMenu: false
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      sources:
        - 'volume:d4cdab7c-bb04-4a50-bea1-4fe6353344c0' # Logos
        - 'volume:c5e90cc1-dc82-4470-8eb6-b462dbb75259' # Images
      targetSiteId: null
      validateRelatedElements: false
      viewMode: large
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  723399b6-47d6-4bd9-b59a-c61c56cdaa44: # Kopfzeile
    columnSuffix: uyxpjhxc
    contentColumnType: text
    fieldGroup: null
    handle: heading
    instructions: 'Leer lassen, falls nicht benötigt.'
    name: Kopfzeile
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: language
    type: craft\fields\PlainText
  f7c1d3c4-fb65-4ead-83b4-ee3cf63d98e3: # Text
    columnSuffix: btklxntm
    contentColumnType: text
    fieldGroup: null
    handle: text
    instructions: null
    name: Text
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: true
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: language
    type: craft\fields\PlainText
