fieldLayouts:
  37789832-348d-4d44-a413-87ffe26c26bb:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 35853a03-a023-42a1-a246-59b04b4a1433 # Logo Deutsch
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 18cae84a-12aa-4ebe-a41e-dc29ff56d7f0
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 2ff8ce56-e1cc-448f-8f64-b75caf2e1106 # Logo Französisch
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6c6cec05-e26d-4463-92fb-a2e2fc754ff4
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 2ae5d2b3-577a-4914-9d60-0e8294bc5301 # Logo Jacobsfundation
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: be4800fe-2793-4afe-9300-bd99537f3994
            userCondition: null
            warning: null
            width: 100
        name: Branding
        uid: 311df809-7b75-47f0-9fe4-766d144a591a
        userCondition: null
handle: branding
name: Branding
sortOrder: 1
