defaultPlacement: end
enableVersioning: true
handle: blog
name: Blog
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primäre eintrag Seite'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  ac1d573d-4c9a-4de1-a431-172e73f30817: # Französisch
    enabledByDefault: true
    hasUrls: true
    template: _pages/blog-post.twig
    uriFormat: 'blog/{slug}'
  e6d6312f-5bfe-4933-80d2-be986487da24: # Deutsch
    enabledByDefault: true
    hasUrls: true
    template: _pages/blog-post.twig
    uriFormat: 'blog/{slug}'
type: channel
